// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXrftckloRsU_EKOA_oMgI-9BJdV4kIQs',
    appId: '1:735357850346:web:8e4df3128477e90e64bd93',
    messagingSenderId: '735357850346',
    projectId: 'volley-track-dev-4596c',
    authDomain: 'volley-track-dev-4596c.firebaseapp.com',
    storageBucket: 'volley-track-dev-4596c.firebasestorage.app',
    measurementId: 'G-8Z0QYPBRNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnx96in04GGDqqHMUI87Xe_kN4f6fUZ0s',
    appId: '1:735357850346:android:9baf04babaaea15964bd93',
    messagingSenderId: '735357850346',
    projectId: 'volley-track-dev-4596c',
    storageBucket: 'volley-track-dev-4596c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCirotx5Z0b3UiwuwXDZx-uha5_bDco1Y',
    appId: '1:735357850346:ios:adb6880d5e7bcf3d64bd93',
    messagingSenderId: '735357850346',
    projectId: 'volley-track-dev-4596c',
    storageBucket: 'volley-track-dev-4596c.firebasestorage.app',
    androidClientId: '735357850346-rdfkui80a3lp79gataa88d112egltju1.apps.googleusercontent.com',
    iosClientId: '735357850346-gfp95q15ctt1v54lslk23oun4h9jalmd.apps.googleusercontent.com',
    iosBundleId: 'br.com.nexago.nexagoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCirotx5Z0b3UiwuwXDZx-uha5_bDco1Y',
    appId: '1:735357850346:ios:adb6880d5e7bcf3d64bd93',
    messagingSenderId: '735357850346',
    projectId: 'volley-track-dev-4596c',
    storageBucket: 'volley-track-dev-4596c.firebasestorage.app',
    androidClientId: '735357850346-rdfkui80a3lp79gataa88d112egltju1.apps.googleusercontent.com',
    iosClientId: '735357850346-gfp95q15ctt1v54lslk23oun4h9jalmd.apps.googleusercontent.com',
    iosBundleId: 'br.com.nexago.nexagoApp',
  );
}
