import type { AthleteDirectoryEntry } from './athlete-directory.models';

/**
 * Elenco fictício compartilhado entre Atletas, Ranking, Equipes e Perfil público —
 * mesmos nomes/handles/cidades/níveis em todas as telas pra parecer uma comunidade real.
 */
export const MOCK_ATHLETE_DIRECTORY: readonly AthleteDirectoryEntry[] = [
  {
    id: 'rafanunes',
    handle: 'rafanunes',
    fullName: 'Rafaela Nunes',
    city: 'Goiânia, GO',
    distanceKm: 5,
    sport: 'beachVolleyball',
    level: 'Avançado',
    rankingPosition: 1,
    suggestionReason: 'Joga com 2 dos seus parceiros',
  },
  {
    id: 'igormendes',
    handle: 'igormendes',
    fullName: 'Igor Mendes',
    city: 'Aparecida de Goiânia, GO',
    distanceKm: 3,
    sport: 'beachVolleyball',
    level: 'Avançado',
    rankingPosition: 2,
    suggestionReason: 'Perto de você · 3 km',
  },
  {
    id: 'carlam',
    handle: 'carlam',
    fullName: 'Carla Menezes',
    city: 'Goiânia, GO',
    distanceKm: 6,
    sport: 'beachVolleyball',
    level: 'Avançado',
    rankingPosition: 3,
    suggestionReason: 'Jogou com você em 06/06',
  },
  {
    id: 'brunoramos',
    handle: 'brunoramos',
    fullName: 'Bruno Ramos',
    city: 'Goiânia, GO',
    distanceKm: 7,
    sport: 'beachVolleyball',
    level: 'Avançado',
    rankingPosition: 4,
    suggestionReason: null,
  },
  {
    id: 'diegot',
    handle: 'diegot',
    fullName: 'Diego Torres',
    city: 'Trindade, GO',
    distanceKm: 15,
    sport: 'beachVolleyball',
    level: 'Avançado',
    rankingPosition: 5,
    suggestionReason: null,
  },
  {
    id: 'luizf',
    handle: 'luizf',
    fullName: 'Luiz Farias',
    city: 'Goiânia, GO',
    distanceKm: 6,
    sport: 'beachVolleyball',
    level: 'Intermediário',
    rankingPosition: 6,
    suggestionReason: null,
  },
  {
    id: 'carlaalmeida',
    handle: 'carlaalmeida',
    fullName: 'Carla Almeida',
    city: 'Senador Canedo, GO',
    distanceKm: 12,
    sport: 'beachVolleyball',
    level: 'Intermediário',
    rankingPosition: 7,
    suggestionReason: null,
  },
  {
    id: 'jorgerib',
    handle: 'jorgerib',
    fullName: 'Jorge Ribeiro',
    city: 'Goiânia, GO',
    distanceKm: 6,
    sport: 'beachVolleyball',
    level: 'Intermediário',
    rankingPosition: 8,
    suggestionReason: null,
  },
  {
    id: 'enzorib',
    handle: 'enzorib',
    fullName: 'Enzo Ribeiro',
    city: 'Goiânia, GO',
    distanceKm: 6,
    sport: 'beachVolleyball',
    level: 'Intermediário',
    rankingPosition: 9,
    suggestionReason: null,
  },
  {
    id: 'larissac',
    handle: 'larissac',
    fullName: 'Larissa Costa',
    city: 'Aparecida de Goiânia, GO',
    distanceKm: 1,
    sport: 'beachVolleyball',
    level: 'Iniciante',
    rankingPosition: 218,
    suggestionReason: null,
  },
  {
    id: 'pedros',
    handle: 'pedros',
    fullName: 'Pedro Silva',
    city: 'Goiânia, GO',
    distanceKm: 4,
    sport: 'tennis',
    level: 'Iniciante',
    rankingPosition: 340,
    suggestionReason: null,
  },
  {
    id: 'tainan',
    handle: 'tainan',
    fullName: 'Tainá Nunes',
    city: 'Goiânia, GO',
    distanceKm: 6,
    sport: 'beachVolleyball',
    level: 'Intermediário',
    rankingPosition: 112,
    suggestionReason: null,
  },
  {
    id: 'tonhoreis',
    handle: 'tonhoreis',
    fullName: "Antônio 'Tonho' Reis",
    city: 'Goiânia, GO',
    distanceKm: 6,
    sport: 'beachVolleyball',
    level: 'Avançado',
    rankingPosition: 15,
    suggestionReason: null,
  },
];
