import type { DiscoverTeam, MyTeam, PartnerCandidate } from './athlete-equipes.models';

export const MOCK_MY_TEAMS: readonly MyTeam[] = [
  {
    id: 'mt-1',
    memberAInitials: 'MA',
    memberBInitials: 'BR',
    name: 'Marcelo & Bruno V.',
    sport: 'beachVolleyball',
    level: 'Intermediário',
    status: 'fixed',
    wins: 6,
    losses: 4,
    doublesRank: 58,
    pendingNote: null,
  },
  {
    id: 'mt-2',
    memberAInitials: 'MA',
    memberBInitials: 'EN',
    name: 'Marcelo & Enzo',
    sport: 'beachVolleyball',
    level: 'Iniciante',
    status: 'fixed',
    wins: 3,
    losses: 2,
    doublesRank: 140,
    pendingNote: null,
  },
  {
    id: 'mt-3',
    memberAInitials: 'MA',
    memberBInitials: 'DI',
    name: 'Marcelo & Diego T.',
    sport: 'tennis',
    level: 'Iniciante',
    status: 'pending',
    wins: 0,
    losses: 0,
    doublesRank: null,
    pendingNote: 'Aguardando confirmação do parceiro aceitar o convite.',
  },
];

export const MOCK_DISCOVER_TEAMS: readonly DiscoverTeam[] = [
  {
    id: 'dt-1',
    memberAInitials: 'RA',
    memberBInitials: 'TO',
    name: 'Rafa & Tonho',
    sport: 'beachVolleyball',
    level: 'Avançado',
    city: 'Aparecida de Goiânia, GO',
    wins: 18,
    losses: 3,
    doublesRank: 1,
  },
  {
    id: 'dt-2',
    memberAInitials: 'AN',
    memberBInitials: 'BE',
    name: 'Ana R. & Beto L.',
    sport: 'beachVolleyball',
    level: 'Avançado',
    city: 'Goiânia, GO',
    wins: 15,
    losses: 5,
    doublesRank: 2,
  },
  {
    id: 'dt-3',
    memberAInitials: 'CM',
    memberBInitials: 'IM',
    name: 'Carla M. & Igor M.',
    sport: 'beachVolleyball',
    level: 'Avançado',
    city: 'Goiânia, GO',
    wins: 14,
    losses: 6,
    doublesRank: 3,
  },
  {
    id: 'dt-4',
    memberAInitials: 'BR',
    memberBInitials: 'CA',
    name: 'Bruno & Carla A.',
    sport: 'beachVolleyball',
    level: 'Intermediário',
    city: 'Senador Canedo, GO',
    wins: 11,
    losses: 4,
    doublesRank: 4,
  },
  {
    id: 'dt-5',
    memberAInitials: 'DI',
    memberBInitials: 'LF',
    name: 'Diego & Luiz',
    sport: 'beachVolleyball',
    level: 'Intermediário',
    city: 'Trindade, GO',
    wins: 9,
    losses: 5,
    doublesRank: 5,
  },
  {
    id: 'dt-6',
    memberAInitials: 'JR',
    memberBInitials: 'EN',
    name: 'Jorge & Enzo',
    sport: 'beachVolleyball',
    level: 'Intermediário',
    city: 'Goiânia, GO',
    wins: 8,
    losses: 6,
    doublesRank: 6,
  },
];

export const MOCK_PARTNER_CANDIDATES: readonly PartnerCandidate[] = [
  {
    id: 'pc-1',
    initials: 'LC',
    name: 'Larissa Costa',
    locationLabel: 'Aparecida de Goiânia',
    distanceKm: 1,
    level: 'Iniciante',
    sport: 'beachVolleyball',
    availabilityTag: 'flexible',
    note: 'Joga terças e sábados',
  },
  {
    id: 'pc-2',
    initials: 'PS',
    name: 'Pedro Silva',
    locationLabel: 'Goiânia, 4 km',
    distanceKm: 4,
    level: 'Iniciante',
    sport: 'beachVolleyball',
    availabilityTag: 'night',
    note: 'Disponível à noite',
  },
  {
    id: 'pc-3',
    initials: 'TN',
    name: 'Tainá Nunes',
    locationLabel: 'Goiânia, 6 km',
    distanceKm: 6,
    level: 'Intermediário',
    sport: 'beachVolleyball',
    availabilityTag: 'flexible',
    note: 'Procura dupla p/ torneio',
  },
  {
    id: 'pc-4',
    initials: 'VM',
    name: 'Vitor Melo',
    locationLabel: 'Sen. Canedo, 9 km',
    distanceKm: 9,
    level: 'Iniciante',
    sport: 'beachVolleyball',
    availabilityTag: 'weekend',
    note: 'Fins de semana',
  },
  {
    id: 'pc-5',
    initials: 'GA',
    name: 'Gabriela Alves',
    locationLabel: 'Goiânia, 3 km',
    distanceKm: 3,
    level: 'Iniciante',
    sport: 'beachVolleyball',
    availabilityTag: 'flexible',
    note: 'Joga quartas e sábados',
  },
  {
    id: 'pc-6',
    initials: 'RF',
    name: 'Rodrigo Faria',
    locationLabel: 'Trindade, 12 km',
    distanceKm: 12,
    level: 'Intermediário',
    sport: 'beachTennis',
    availabilityTag: 'flexible',
    note: 'Aberto a desafios',
  },
];
