import type { DiscoveryLeague, DiscoveryTournament } from './tournament-discovery.models';

function d(days: number, h = 12, m = 0): Date {
  const x = new Date();
  x.setDate(x.getDate() + days);
  x.setHours(h, m, 0, 0);
  return x;
}

const LIGA_VERAO = 'circuito-verao-nexago-2026';
const ETAPA_NORDESTE = 'cv-26-nordeste';
const ETAPA_SUDESTE = 'cv-26-sudeste';

const LIGA_GOIAS_BEACH = 'copa-goias-beach-2026';
const ETAPA_APARECIDA = 'cgb-26-aparecida';

/** Ligas com etapas; cada etapa lista ids de `MOCK_DISCOVERY_TOURNAMENTS`. */
export const MOCK_DISCOVERY_LEAGUES: DiscoveryLeague[] = [
  {
    id: LIGA_VERAO,
    name: 'Circuito Verão NexaGO',
    seasonLabel: 'Temporada 2026',
    city: 'Circuito nacional',
    stages: [
      {
        id: ETAPA_NORDESTE,
        name: 'Etapa Nordeste',
        order: 1,
        dateLabel: 'Abr–mai',
        tournamentIds: ['nx-beach-pro-2026', 'ranked-friday-recife'],
      },
      {
        id: ETAPA_SUDESTE,
        name: 'Etapa Sudeste',
        order: 2,
        dateLabel: 'Jun–jul',
        tournamentIds: ['night-open-sp', 'circuito-verao-rj'],
      },
    ],
  },
  {
    id: LIGA_GOIAS_BEACH,
    name: 'Copa Goiás Beach 2026',
    seasonLabel: 'Fevereiro a Outubro de 2026',
    city: '6 cidades · GO/DF',
    stages: [
      {
        id: ETAPA_APARECIDA,
        name: 'Etapa Aparecida',
        order: 3,
        dateLabel: '18 – 20 abr',
        tournamentIds: ['etapa-aparecida-goias-beach'],
      },
    ],
  },
];

export const MOCK_DISCOVERY_TOURNAMENTS: DiscoveryTournament[] = [
  {
    id: 'nx-beach-pro-2026',
    name: 'NexaGO Beach Pro Series',
    location: 'Arena NexaGO Sul',
    city: 'Salvador',
    dateLabel: '18–20 abr',
    startDate: d(8, 8, 0),
    categories: ['M', 'F', 'Mix'],
    format: 'Dupla',
    priceLabel: 'R$ 240',
    priceValue: 240,
    spotsLeft: 3,
    spotsTotal: 64,
    status: 'almost_full',
    featured: true,
    enrolledCount: 428,
    liveMatchesNow: 0,
    enrolled: false,
    registrationOpensAt: null,
    leagueId: LIGA_VERAO,
    leagueStageId: ETAPA_NORDESTE,
  },
  {
    id: 'night-open-sp',
    name: 'Night Open São Paulo',
    location: 'Praia Artificial Pinheiros',
    city: 'São Paulo',
    dateLabel: '12 abr',
    startDate: d(2, 19, 0),
    categories: ['Mix', 'F'],
    format: 'Dupla',
    priceLabel: 'R$ 180',
    priceValue: 180,
    spotsLeft: 14,
    spotsTotal: 48,
    status: 'open',
    featured: true,
    enrolledCount: 186,
    liveMatchesNow: 6,
    enrolled: false,
    registrationOpensAt: null,
    leagueId: LIGA_VERAO,
    leagueStageId: ETAPA_SUDESTE,
  },
  {
    id: 'circuito-verao-rj',
    name: 'Circuito Verão RJ',
    location: 'Arena Copacabana Sports',
    city: 'Rio de Janeiro',
    dateLabel: '25 abr – 2 mai',
    startDate: d(15, 9, 0),
    categories: ['M', 'F'],
    format: 'Dupla',
    priceLabel: 'R$ 320',
    priceValue: 320,
    spotsLeft: 22,
    spotsTotal: 96,
    status: 'open',
    featured: false,
    enrolledCount: 312,
    liveMatchesNow: 0,
    enrolled: true,
    registrationOpensAt: null,
    leagueId: LIGA_VERAO,
    leagueStageId: ETAPA_SUDESTE,
  },
  {
    id: 'flash-individual-bh',
    name: 'Flash Individual BH',
    location: 'Centro de Treino Minas Beach',
    city: 'Belo Horizonte',
    dateLabel: '10 abr',
    startDate: d(0, 14, 0),
    categories: ['M', 'F', 'Mix'],
    format: 'Individual',
    priceLabel: 'R$ 95',
    priceValue: 95,
    spotsLeft: 8,
    spotsTotal: 32,
    status: 'live',
    featured: false,
    enrolledCount: 94,
    liveMatchesNow: 4,
    enrolled: false,
    registrationOpensAt: null,
  },
  {
    id: 'misto-experience-floripa',
    name: 'Misto Experience Floripa',
    location: 'Arena Jurerê Internacional',
    city: 'Florianópolis',
    dateLabel: '6 mai',
    startDate: d(26, 10, 0),
    categories: ['Mix'],
    format: 'Dupla',
    priceLabel: 'R$ 210',
    priceValue: 210,
    spotsLeft: 28,
    spotsTotal: 40,
    status: 'open',
    featured: false,
    enrolledCount: 72,
    liveMatchesNow: 0,
    enrolled: false,
    registrationOpensAt: d(10, 9, 0),
  },
  {
    id: 'open-goiania-beach',
    name: 'Open Goiânia Beach',
    location: 'Arena ErreJota',
    city: 'Goiânia',
    dateLabel: '28 – 30 ago',
    startDate: d(51, 8, 0),
    categories: ['F', 'M', 'Mix'],
    format: 'Dupla',
    priceLabel: 'R$ 150',
    priceValue: 150,
    spotsLeft: 34,
    spotsTotal: 72,
    status: 'open',
    featured: true,
    enrolledCount: 76,
    liveMatchesNow: 0,
    enrolled: false,
    registrationOpensAt: null,
  },
  {
    id: 'ranked-friday-recife',
    name: 'Ranked Friday Recife',
    location: 'Boa Viagem Beach Arena',
    city: 'Recife',
    dateLabel: '11 abr',
    startDate: d(1, 20, 30),
    categories: ['M', 'F', 'Mix'],
    format: 'Dupla',
    priceLabel: 'R$ 120',
    priceValue: 120,
    spotsLeft: 0,
    spotsTotal: 24,
    status: 'ended',
    featured: false,
    enrolledCount: 128,
    liveMatchesNow: 0,
    enrolled: false,
    registrationOpensAt: null,
    leagueId: LIGA_VERAO,
    leagueStageId: ETAPA_NORDESTE,
  },
  {
    id: 'etapa-aparecida-goias-beach',
    name: 'Etapa Aparecida · Copa Goiás Beach',
    location: 'Arena Aparecida Beach',
    city: 'Aparecida de Goiânia',
    dateLabel: '18 – 20 abr',
    startDate: d(21, 8, 0),
    categories: ['M', 'F', 'Mix'],
    format: 'Dupla',
    priceLabel: 'R$ 90',
    priceValue: 90,
    spotsLeft: 28,
    spotsTotal: 48,
    status: 'open',
    featured: false,
    enrolledCount: 20,
    liveMatchesNow: 0,
    enrolled: false,
    registrationOpensAt: null,
    leagueId: LIGA_GOIAS_BEACH,
    leagueStageId: ETAPA_APARECIDA,
  },
];

export const MOCK_LIVE_STATS = {
  activeTournaments: 14,
  playersOnline: 1284,
  matchesLiveNow: 23,
};
