import type { DiscoveryLeague, DiscoveryTournament } from './tournament-discovery.models';

function d(days: number, h = 12, m = 0): Date {
  const x = new Date();
  x.setDate(x.getDate() + days);
  x.setHours(h, m, 0, 0);
  return x;
}

const LIGA_VERAO = 'circuito-verao-nexago-2026';
const ETAPA_NORDESTE = 'cv-26-nordeste';
const ETAPA_SUDESTE = 'cv-26-sudeste';

/** Ligas com etapas; cada etapa lista ids de `MOCK_DISCOVERY_TOURNAMENTS`. */
export const MOCK_DISCOVERY_LEAGUES: DiscoveryLeague[] = [
  {
    id: LIGA_VERAO,
    name: 'Circuito Verão NexaGO',
    seasonLabel: 'Temporada 2026',
    city: 'Circuito nacional',
    stages: [
      {
        id: ETAPA_NORDESTE,
        name: 'Etapa Nordeste',
        order: 1,
        dateLabel: 'Abr–mai',
        tournamentIds: ['nx-beach-pro-2026', 'ranked-friday-recife'],
      },
      {
        id: ETAPA_SUDESTE,
        name: 'Etapa Sudeste',
        order: 2,
        dateLabel: 'Jun–jul',
        tournamentIds: ['night-open-sp', 'circuito-verao-rj'],
      },
    ],
  },
];

export const MOCK_DISCOVERY_TOURNAMENTS: DiscoveryTournament[] = [
  {
    id: 'nx-beach-pro-2026',
    name: 'NexaGO Beach Pro Series',
    location: 'Arena NexaGO Sul',
    city: 'Salvador',
    dateLabel: '18–20 abr',
    startDate: d(8, 8, 0),
    categories: ['M', 'F', 'Mix'],
    format: 'Dupla',
    priceLabel: 'R$ 240',
    priceValue: 240,
    spotsLeft: 3,
    spotsTotal: 64,
    status: 'almost_full',
    featured: true,
    enrolledCount: 428,
    liveMatchesNow: 0,
    offerEndsAt: d(2, 23, 59),
    leagueId: LIGA_VERAO,
    leagueStageId: ETAPA_NORDESTE,
  },
  {
    id: 'night-open-sp',
    name: 'Night Open São Paulo',
    location: 'Praia Artificial Pinheiros',
    city: 'São Paulo',
    dateLabel: '12 abr',
    startDate: d(2, 19, 0),
    categories: ['Mix', 'F'],
    format: 'Dupla',
    priceLabel: 'R$ 180',
    priceValue: 180,
    spotsLeft: 14,
    spotsTotal: 48,
    status: 'open',
    featured: true,
    enrolledCount: 186,
    liveMatchesNow: 6,
    offerEndsAt: null,
    leagueId: LIGA_VERAO,
    leagueStageId: ETAPA_SUDESTE,
  },
  {
    id: 'circuito-verao-rj',
    name: 'Circuito Verão RJ',
    location: 'Arena Copacabana Sports',
    city: 'Rio de Janeiro',
    dateLabel: '25 abr – 2 mai',
    startDate: d(15, 9, 0),
    categories: ['M', 'F'],
    format: 'Dupla',
    priceLabel: 'R$ 320',
    priceValue: 320,
    spotsLeft: 22,
    spotsTotal: 96,
    status: 'open',
    featured: false,
    enrolledCount: 312,
    liveMatchesNow: 0,
    offerEndsAt: d(5, 12, 0),
    leagueId: LIGA_VERAO,
    leagueStageId: ETAPA_SUDESTE,
  },
  {
    id: 'flash-individual-bh',
    name: 'Flash Individual BH',
    location: 'Centro de Treino Minas Beach',
    city: 'Belo Horizonte',
    dateLabel: '10 abr',
    startDate: d(0, 14, 0),
    categories: ['M', 'F', 'Mix'],
    format: 'Individual',
    priceLabel: 'R$ 95',
    priceValue: 95,
    spotsLeft: 8,
    spotsTotal: 32,
    status: 'live',
    featured: false,
    enrolledCount: 94,
    liveMatchesNow: 4,
    offerEndsAt: null,
  },
  {
    id: 'misto-experience-floripa',
    name: 'Misto Experience Floripa',
    location: 'Arena Jurerê Internacional',
    city: 'Florianópolis',
    dateLabel: '6 mai',
    startDate: d(26, 10, 0),
    categories: ['Mix'],
    format: 'Dupla',
    priceLabel: 'R$ 210',
    priceValue: 210,
    spotsLeft: 28,
    spotsTotal: 40,
    status: 'open',
    featured: false,
    enrolledCount: 72,
    liveMatchesNow: 0,
    offerEndsAt: null,
  },
  {
    id: 'ranked-friday-recife',
    name: 'Ranked Friday Recife',
    location: 'Boa Viagem Beach Arena',
    city: 'Recife',
    dateLabel: '11 abr',
    startDate: d(1, 20, 30),
    categories: ['M', 'F', 'Mix'],
    format: 'Dupla',
    priceLabel: 'R$ 120',
    priceValue: 120,
    spotsLeft: 0,
    spotsTotal: 24,
    status: 'ended',
    featured: false,
    enrolledCount: 128,
    liveMatchesNow: 0,
    offerEndsAt: null,
    leagueId: LIGA_VERAO,
    leagueStageId: ETAPA_NORDESTE,
  },
];

export const MOCK_LIVE_STATS = {
  activeTournaments: 14,
  playersOnline: 1284,
  matchesLiveNow: 23,
};
